### ISSUE TITLE
Crashes with resolution values less than 1m

### ISSUE THREAD

**Issue by geojed** [tue-alga/topotide#1]
I was doing some sensitivity analysis at different resolutions and found that when the resolution is set to a  value less than 1m (in my case 0.5m for the X & Y) that the program crashes during the MS Complex Simplification stage. I imagine this wont matter for most use cases, but could be worth adding a note in the documentation

**Comment by Willem3141** [comment]
Hi jededale, thanks for using our software! Resolutions smaller than 1m should just work, so I'm not sure what exactly is going wrong here. I'll investigate and let you know.

**Comment by geojed** [comment]
Yeah I'm not sure if's the root of the issue. But I've recreated the issue with both sample data from the paper, and my own topographic data, and it doesn't seem to always fail at <1m but I've ha situations where the same input runs fine with 1m resolution but fails at 0.5m. I've also encountered it using both image and text input files. I've seen slight variations, but the most common error message upon failure is bellow. And thanks for your work on this software, I've just been playing with it a few days but see alot of diverse research potential!

`ttga: /home/$USER/src/ttga/src/mscomplexcreator.cpp:256: MsComplexCreator::setDcelMsFacesAroundMinimum(Dcel<MsVertex, MsHalfEdge, MsFace>::Vertex)::<lambda(Dcel<MsVertex, MsHalfEdge, MsFace>::HalfEdge)>: Assertion 'p2.edges()[k].twin().data().incidentMsFace == -1' failed.`

**Comment by geojed** [comment]
For an example using the 'Braided_River_A46_11_timestep094.png' input file and the Persistence based algorithm successfully runs at 1m in the X&Y  and fails at 0.5m in the X&Y fails with:

`tga: /home/dale/src/ttga/src/mscomplexcreator.cpp:250: MsComplexCreator::setDcelMsFacesAroundMinimum(Dcel<MsVertex, MsHalfEdge, MsFace>::Vertex)::<lambda(Dcel<MsVertex, MsHalfEdge, MsFace>::HalfEdge)>: Assertion 'p1.edges()[k].data().incidentMsFace == -1' failed.
`

**Comment by Willem3141** [comment]
Thanks for the additional information. I am able to reproduce the crash now and will investigate it further.

> I've just been playing with it a few days but see alot of diverse research potential!

That's great to hear! :slightly_smiling_face:

**Comment by Willem3141** [comment]
I found the cause of the issue and fixed it locally. I'll release a new fixed version tomorrow.

**Comment by Willem3141** [comment]
Version 1.4.1 should fix it. Please re-open this issue if you still have issues.
