### ISSUE TITLE
Issues Running 1.5.0

### ISSUE THREAD

**Issue by sschooler** [tue-alga/topotide#2]
Hello, after downloading version 1.5.0 and unzipping, I attempt to run the GUI and get some errors. The errors include the text "The code execution cannot proceed because libstdcc++-6.dll was not found. Reinstalling the program may fix this problem." where there are multiple files instead of libstdcc++-6.dll.
The missing files are:
libgcc_s_seh-1.dll
libstdcc++-6.dll
libdouble-conversion.dll

Is there some sort of compilation I need to do before running the program?

I'm running on Windows 11 Pro version 10.0.22621

Thanks!

**Comment by Willem3141** [comment]
Hi, sorry for the delayed response! I've just released version 1.5.1 ([here](https://github.com/tue-alga/ttga/releases/tag/v1.5.1)) which should resolve this issue. Please give it a try. I'll close this issue for now, but if it turns out you still have the same issue, feel free to re-open it.
